name: Build LaTeX document
on: [ push ]
jobs:
  generate_resume_pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          latexmk_use_lualatex: true
          root_file: Biswambar_Pradhan_Resume.tex
          extra_fonts: |
            ./fonts/*.ttf
        env:
          TEXINPUTS: ".:./mcdowellcv.cls//:"

      - name: Release_PDF
        uses: softprops/action-gh-release@v2
        with:
          files: Biswambar_Pradhan_Resume.pdf
