name: Build LaTeX document
on: [push]
jobs:
  generate_resume_pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          latexmk_use_lualatex: true
          root_file: Biswambar_Pradhan_Resume.tex
          extra_fonts: |
            ./fonts/*.ttf
        env:
          TEXINPUTS: ".:./mcdowellcv.cls//:"
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: Biswambar_Pradhan_Resume.pdf